### PR TITLE
Updated Vagrantfile for Vagrant API version 2

### PR DESCRIPTION
**Pull request by robjmills**
Updates to latest Vagrant API version - provider specific code (in this case for virtual box) is now self-contained as per the new spec

### CODE REVIEW

**Comment by gmanricks** [comment]
These updates work great, and I like what you did with the network. I am just going to update the stagr CLI to reflect the new settings.

Currently you have to add the host to your local hosts file, and then you can access your site at http://demo.dev (or whatever you named it. With this new setup you add 127.0.0.1 to your hosts file with the domain of your app, and then you access it with http://demo.dev:8080

I will add the changes and then pull this in tomorrow morning

**Comment by robjmills** [comment]
The port 8080 version is how I tend to do things but I noticed afterwards that this would cause an issue with the stagr CLI so I pushed an update that would work more like your original version to prevent you needing to update your app. I'll let you make the call on which is the better option :)

**Comment by gmanricks** [comment]
Haha thanks :) The old way has cleaner URLs as you don't need to specify the port, but what you lose in that respect you gain in setup, before it would list all the network interfaces, and you had to guess the right one (unless you were familiar with your network). The new way I can just hard code the 127.0.0.1 ip and make it simpler to use I think. Unless you think there is another reason to use the old way ?

**Comment by gmanricks** [comment]
Anyways I'll merge this version now, and try and update the app tomorrow morning. Also could you send me your info (website, etc..) so I can update the Stagr site as-well http://gabrielmanricks.com/contact

**Pull request merged**
